import { ReactNode } from "react";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/context/ThemeProvider";
import "@/styles/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: rawParams, // Меняем имя, чтобы потом не было проблем
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  // Делаем params асинхронным
  const params = await Promise.resolve(rawParams);

  // Теперь можно спокойно использовать params.locale
  const detectedLocale = params.locale || "ru";

  // Загружаем переводы
  const messages = await getMessages({ locale: detectedLocale });

  return (
    <html lang={detectedLocale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={detectedLocale} messages={messages}>
          <ThemeProvider>
            <Navbar />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
